name: cardiosense-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.2
  - torchvision=0.17
  - torchaudio=2.2
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - seaborn
  - ipykernel
