name: cardiosense-cpu
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.2
  - torchvision=0.17
  - torchaudio=2.2
  - cpuonly
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - seaborn
  - ipykernel
